name: Release Tag

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/maven.yml
  release-tag:
    name: Release Tag
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: satchecking
      - name: Rename artifact
        env:
          tag: ${{ github.ref_name }}
        run: mv satchecking-*.jar satchecking-v${tag#v}.jar
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" satchecking-v${tag#v}.jar \
              --repo="$GITHUB_REPOSITORY" \
              --title="v${tag#v}"